spring:
  application:
    name: XTarefas
  jpa:
    database: POSTGRESQL
    show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: dd-MM-yyyy
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5429/xtarefas
    username: xtarefas
    password: xtarefas
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    drop-first: true
application:
  feign:
    url-documents: http://localhost:8081


    spring:
      data:
        jest:
          uri: http://elasticsearch-cliente.elasticsearch:9200
      datasource:
        password: $ESi&HoJbhd0
        url: jdbc:sqlserver://sqldes.basis.intern:1433;database=SICASE
        username: app_sicase
      elasticsearch:
        rest:
          uris: http://elasticsearch-cliente.elasticsearch:9200
      profiles:
        active: prod,swagger,local
      redis:
        host: redis-headless.redis
        port: 6379
      liquibase:
        drop-first: true